services:
  caceis-extract:
    build: .
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - SHARED_MAILBOX=${SHARED_MAILBOX}
      - SCOPES=${SCOPES}
      - PASSWORD_MAILBOX=${PASSWORD_MAILBOX}
      - URL_SHARE_POINT=${URL_SHARE_POINT}
      - SHAREPOINT_FOLDER_PDF_MENSUELLE=${SHAREPOINT_FOLDER_PDF_MENSUELLE}
      - SHAREPOINT_FOLDER_PDF_QUOTIDIEN=${SHAREPOINT_FOLDER_PDF_QUOTIDIEN}
      - SHAREPOINT_FOLDER_EXCEL_MENSUELLE=${SHAREPOINT_FOLDER_EXCEL_MENSUELLE}
      - SHAREPOINT_FOLDER_EXCEL_QUOTIDIEN=${SHAREPOINT_FOLDER_EXCEL_QUOTIDIEN}
      - SHAREPOINT_SITE_URL=${SHAREPOINT_SITE_URL}
      - PATH_LOGIN_FILE=${PATH_LOGIN_FILE}
      - SHEET_LOGIN_NAME=${SHEET_LOGIN_NAME}
      - LOCAL_PATH_LOGIN_FILE_SHEET=${LOCAL_PATH_LOGIN_FILE_SHEET}
      - SENDER=${SENDER}
      